version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "UTC"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
      include: "scope"
