title = "Noticiencias Secret Scan"

[allowlist]
description = "Ignore known non-sensitive fixtures and generated assets."
paths = [
  '''^tests/data/''',
  '''^tests/test_security_gate.py$''',
  '''^docs/fixtures/''',
  '''^docs/examples/''',
  '''^reports/''',
  '''^\.venv/''',
]
regexes = [
  '''dummy(_|-)secret''',
  '''test(_|-)api(_|-)key''',
]
commits = [
  "9c9bdf23e48ba2d0154d59404eac61b29ce24a40",
  "bce631a5ec1c61accc83700ae5ed47e84f1ec832",
]

[[rules]]
id = "generic-api-key"
description = "Generic API or secret token"
regex = '''(?i)(api|token|secret|key)["'=:\s]+[A-Za-z0-9_\-]{16,}'''
secretGroup = 0
tags = ["secret", "generic"]
