[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.ruff]
line-length = 100
target-version = "py311"
src = ["src", "tests"]

[tool.ruff.lint]
select = ["E", "F"]
ignore = ["E203", "E402", "E501"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
warn_unused_configs = true
follow_imports = "skip"

[[tool.mypy.overrides]]
module = ["config.*"]
ignore_errors = true

[[tool.mypy.overrides]]
module = [
    "src.storage.*",
    "src.scoring.*",
    "src.collectors.*",
    "src.enrichment.*",
    "src.reranker.*",
    "src.utils.logger",
    "src.utils.observability",
]
ignore_errors = true

[tool.coverage.run]
branch = true
source = ["src"]
omit = ["tests/*"]

[tool.coverage.report]
show_missing = true
skip_covered = true
fail_under = 30

[tool.coverage.xml]
output = "reports/coverage.xml"

[tool.pytest.ini_options]
addopts = "--cov=src --cov-report=xml:reports/coverage.xml --cov-report=term-missing --cov-fail-under=30"
testpaths = ["tests"]

[tool.uv]
managed = false
