"""Initial schema

Revision ID: cb486d1d980d
Revises:
Create Date: 2025-12-31 13:27:02.756495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb486d1d980d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.alter_column('suppressed_until',
                   existing_type=sa.TIMESTAMP(),
                   type_=sa.DateTime(timezone=True),
                   existing_nullable=True)
        batch_op.alter_column('auto_suppressed',
                   existing_type=sa.INTEGER(),
                   type_=sa.Boolean(),
                   existing_nullable=True,
                   existing_server_default=sa.text('0'))
        batch_op.alter_column('last_canary_check',
                   existing_type=sa.TIMESTAMP(),
                   type_=sa.DateTime(timezone=True),
                   existing_nullable=True)
        batch_op.alter_column('last_canary_status',
                   existing_type=sa.TEXT(),
                   type_=sa.String(length=20),
                   existing_nullable=True)
        batch_op.alter_column('feed_etag',
                   existing_type=sa.TEXT(),
                   type_=sa.String(length=512),
                   existing_nullable=True)
        batch_op.alter_column('feed_last_modified',
                   existing_type=sa.TEXT(),
                   type_=sa.String(length=100),
                   existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sources', 'feed_last_modified',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('sources', 'feed_etag',
               existing_type=sa.String(length=512),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('sources', 'last_canary_status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('sources', 'last_canary_check',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('sources', 'auto_suppressed',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('sources', 'suppressed_until',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###
