"""Backend-driven validation of generated publication artifacts against the frontend."""

from __future__ import annotations

import json
import subprocess
import time
from datetime import date, datetime, timezone
from pathlib import Path
from typing import Callable, Sequence

from news_collector.contracts import MANIFEST_FILENAME
from news_collector.contracts.frontend_schema import AstroPost
from news_collector.contracts.publication_validation import (
    FrontendCheckResult,
    PublicationFailureClass,
    PublicationValidationSummary,
)

FIXTURE_ARTICLE_ID = "smoke-test-ci-fixture"
FIXTURE_POST_FILENAME = "_smoke-test.md"

CommandRunner = Callable[[Sequence[str], Path], subprocess.CompletedProcess[str]]


def build_fixture_post() -> AstroPost:
    return AstroPost(
        title="Publication Smoke Test Article",
        schema_version=1,
        excerpt=(
            "This is a synthetic fixture article generated by the CI publication "
            "smoke test to verify cross-repo publication compatibility."
        ),
        author="Noticiencias",
        date=date(2026, 1, 1),
        categories=["Ciencia"],
        tags=["smoke-test"],
        image="https://example.com/placeholder.jpg",
        image_alt="Smoke test placeholder image",
        permalink="/smoke-test-ci-fixture/",
        investigation=False,
        featured=False,
    )


def render_fixture_markdown(post: AstroPost) -> str:
    lines: list[str] = ["---"]
    lines.append(f"title: {post.title!r}")
    lines.append(f"schema_version: {post.schema_version}")
    lines.append(f"excerpt: {post.excerpt!r}")
    lines.append(f"author: {post.author!r}")
    lines.append(f"date: {post.date}")
    lines.append(f"categories: [{', '.join(f'{c!r}' for c in post.categories)}]")
    lines.append(f"tags: [{', '.join(f'{t!r}' for t in post.tags)}]")
    lines.append(f"image: {post.image!r}")
    lines.append(f"image_alt: {post.image_alt!r}")
    if post.permalink:
        lines.append(f"permalink: {post.permalink!r}")
    lines.append(f"investigation: {str(post.investigation).lower()}")
    lines.append(f"featured: {str(post.featured).lower()}")
    lines.append("---")
    lines.append("")
    lines.append(
        "Smoke test fixture only. "
        "This article is generated automatically by the backend publication validation "
        "runner to prove that the current publication contract produces a post that passes "
        "the real frontend quality, build, and audit gates. "
        "It is intentionally synthetic, long enough to satisfy content-quality checks, "
        "and uses a remote placeholder image so the frontend does not require a new local "
        "image derivative manifest entry for this fixture. "
        "The runner also maintains a consistent refinery manifest sidecar while the fixture "
        "exists, then restores the workspace after validation completes."
    )
    lines.append("")
    return "\n".join(lines)


def _default_command_runner(
    command: Sequence[str], cwd: Path
) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        list(command),
        cwd=str(cwd),
        text=True,
        capture_output=True,
        check=False,
    )


def _classify_failure(
    check_name: str,
    output: str,
) -> PublicationFailureClass:
    lowered = output.lower()
    if (
        "duplicate permalink" in lowered
        or "permalink" in lowered
        and "duplicate" in lowered
    ):
        return "permalink_collision"
    if (
        "[check:tags]" in lowered
        or "tag violations" in lowered
        or "tag contains disallowed" in lowered
        or "categories" in lowered
        or "tags" in lowered
        or "taxonomy" in lowered
    ):
        return "taxonomy_contract_violation"
    if (
        "refinery_manifest" in lowered
        or "published content sidecar check found" in lowered
        or "stale manifest entry" in lowered
        or "escapes posts directory" in lowered
        or "must map to a non-empty filename" in lowered
    ):
        return "sidecar_missing_or_malformed"
    if check_name == "build":
        return "frontend_build_failure"
    if check_name == "test_dist":
        return "frontend_dist_failure"
    if check_name == "test_audit":
        return "frontend_audit_failure"
    return "schema_mismatch"


def _load_manifest(manifest_path: Path) -> tuple[dict[str, str], str | None]:
    if not manifest_path.exists():
        return {}, None
    original_text = manifest_path.read_text(encoding="utf-8")
    parsed = json.loads(original_text)
    if not isinstance(parsed, dict):
        raise ValueError("refinery manifest must be a JSON object")
    normalized = {
        str(key): str(value)
        for key, value in parsed.items()
        if isinstance(key, str) and isinstance(value, str)
    }
    return normalized, original_text


def _stage_fixture(frontend_root: Path) -> dict[str, str | None]:
    posts_dir = frontend_root / "src" / "content" / "posts"
    posts_dir.mkdir(parents=True, exist_ok=True)
    post_path = posts_dir / FIXTURE_POST_FILENAME
    manifest_path = posts_dir / MANIFEST_FILENAME

    manifest, original_manifest_text = _load_manifest(manifest_path)
    manifest[FIXTURE_ARTICLE_ID] = FIXTURE_POST_FILENAME

    post_path.write_text(
        render_fixture_markdown(build_fixture_post()), encoding="utf-8"
    )
    manifest_path.write_text(
        f"{json.dumps(manifest, indent=2, sort_keys=True)}\n", encoding="utf-8"
    )

    return {
        "post_path": str(post_path),
        "manifest_path": str(manifest_path),
        "original_manifest_text": original_manifest_text,
    }


def _cleanup_fixture(frontend_root: Path, staged: dict[str, str | None]) -> None:
    post_path = Path(staged["post_path"] or "")
    manifest_path = Path(staged["manifest_path"] or "")
    if post_path.exists():
        post_path.unlink()

    original_manifest_text = staged.get("original_manifest_text")
    if original_manifest_text is None:
        if manifest_path.exists():
            manifest_path.unlink()
        return

    manifest_path.write_text(original_manifest_text, encoding="utf-8")


def _record_check(
    name: str,
    command: Sequence[str],
    cwd: Path,
    runner: CommandRunner,
) -> FrontendCheckResult:
    started = time.perf_counter()
    completed = runner(command, cwd)
    duration = time.perf_counter() - started
    output = f"{completed.stdout}\n{completed.stderr}".strip()
    success = int(completed.returncode) == 0
    return FrontendCheckResult(
        name=name,
        command=" ".join(command),
        success=success,
        returncode=int(completed.returncode),
        duration_seconds=duration,
        stdout=completed.stdout or "",
        stderr=completed.stderr or "",
        failure_class=None if success else _classify_failure(name, output),
    )


def run_frontend_publication_validation(
    frontend_root: Path,
    *,
    summary_output_path: Path | None = None,
    command_runner: CommandRunner | None = None,
    stage_fixture: bool = True,
    post_path: Path | None = None,
    install_dependencies: bool = True,
) -> PublicationValidationSummary:
    runner = command_runner or _default_command_runner
    root = Path(frontend_root).resolve()
    checks: list[FrontendCheckResult] = []
    manifest_path = root / "src" / "content" / "posts" / MANIFEST_FILENAME

    staged: dict[str, str | None]
    cleanup_fixture = False
    if stage_fixture:
        try:
            staged = _stage_fixture(root)
            cleanup_fixture = True
        except Exception as exc:
            summary = PublicationValidationSummary(
                generated_at=datetime.now(timezone.utc).isoformat(),
                frontend_root=str(root),
                post_path=str(
                    root / "src" / "content" / "posts" / FIXTURE_POST_FILENAME
                ),
                manifest_path=str(manifest_path),
                success=False,
                overall_failure_class="sidecar_missing_or_malformed",
                checks=[
                    FrontendCheckResult(
                        name="stage_fixture",
                        command="stage fixture",
                        success=False,
                        returncode=1,
                        stderr=str(exc),
                        failure_class="sidecar_missing_or_malformed",
                    )
                ],
                artifacts={"validation_mode": "fixture"},
            )
            if summary_output_path:
                summary_output_path.parent.mkdir(parents=True, exist_ok=True)
                summary_output_path.write_text(
                    json.dumps(summary.model_dump(mode="json"), indent=2),
                    encoding="utf-8",
                )
            return summary
    else:
        staged = {
            "post_path": str(post_path.resolve()) if post_path else "",
            "manifest_path": str(manifest_path),
            "original_manifest_text": None,
        }

    commands: list[tuple[str, list[str]]] = []
    if install_dependencies:
        commands.append(("npm_ci", ["npm", "ci"]))
    # Generate image derivative manifest entries before lint (which checks them).
    # This ensures new articles with hero images pass check:image-derivatives.
    # Works gracefully without R2 credentials — only produces local manifest entries.
    commands.append(
        (
            "publish_image_derivatives",
            ["npm", "run", "publish:image-derivatives"],
        )
    )
    commands.extend(
        [
            ("lint", ["npm", "run", "lint"]),
            ("validate_content", ["npm", "run", "validate:content"]),
            ("build", ["npm", "run", "build"]),
            ("test_dist", ["npm", "run", "test:dist"]),
            ("test_audit", ["npm", "run", "test:audit"]),
        ]
    )

    overall_failure: PublicationFailureClass | None = None
    try:
        for name, command in commands:
            result = _record_check(name, command, root, runner)
            checks.append(result)
            if not result.success:
                overall_failure = result.failure_class
                break
    finally:
        if cleanup_fixture:
            _cleanup_fixture(root, staged)

    summary = PublicationValidationSummary(
        generated_at=datetime.now(timezone.utc).isoformat(),
        frontend_root=str(root),
        post_path=staged["post_path"] or "",
        manifest_path=staged["manifest_path"] or "",
        success=overall_failure is None,
        overall_failure_class=overall_failure,
        checks=checks,
        artifacts={
            "validation_mode": "fixture" if stage_fixture else "current_state",
            "fixture_article_id": FIXTURE_ARTICLE_ID,
            "fixture_post_filename": FIXTURE_POST_FILENAME,
        },
    )

    if summary_output_path:
        summary_output_path.parent.mkdir(parents=True, exist_ok=True)
        summary_output_path.write_text(
            json.dumps(summary.model_dump(mode="json"), indent=2),
            encoding="utf-8",
        )

    return summary
