"""
generate_fixture_post.py — writes a minimal valid AstroPost MDX fixture file.

Used by the publication smoke-test CI workflow to verify that the current
AstroPost contract produces a file that passes the front-end `validate:content`
check.  The fixture is written to a path supplied via --output; the caller is
responsible for cleaning it up afterwards.

Usage:
    python scripts/generate_fixture_post.py --output ../noticiencias/src/content/posts/_smoke-test.md
"""

from __future__ import annotations

import argparse
import sys
from datetime import date
from pathlib import Path

# Ensure repo root is importable when run as a script
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from news_collector.contracts.frontend_schema import AstroPost  # noqa: E402


def build_fixture() -> AstroPost:
    """Return a minimal valid AstroPost that satisfies all validators."""
    return AstroPost(
        title="Publication Smoke Test Article",
        schema_version=1,
        excerpt="This is a synthetic fixture article generated by the CI publication smoke test to verify schema parity.",
        author="Noticiencias",
        date=date(2026, 1, 1),
        categories=["Ciencia"],
        tags=["smoke-test"],
        image="https://example.com/placeholder.jpg",
        image_alt="Smoke test placeholder image",
        permalink="/smoke-test-ci-fixture/",
        investigation=False,
        featured=False,
    )


def render_frontmatter(post: AstroPost) -> str:
    """Serialize AstroPost fields to YAML frontmatter + empty body."""
    lines: list[str] = ["---"]

    lines.append(f"title: {post.title!r}")
    lines.append(f"schema_version: {post.schema_version}")
    lines.append(f"excerpt: {post.excerpt!r}")
    lines.append(f"author: {post.author!r}")
    lines.append(f"date: {post.date}")

    cats = ", ".join(f"{c!r}" for c in post.categories)
    lines.append(f"categories: [{cats}]")

    tags = ", ".join(f"{t!r}" for t in post.tags)
    lines.append(f"tags: [{tags}]")

    lines.append(f"image: {post.image!r}")
    lines.append(f"image_alt: {post.image_alt!r}")

    if post.permalink:
        lines.append(f"permalink: {post.permalink!r}")

    lines.append(f"investigation: {str(post.investigation).lower()}")
    lines.append(f"featured: {str(post.featured).lower()}")

    lines.append("---")
    lines.append("")
    # Body must satisfy the front-end content quality check (minimum 80 words).
    lines.append(
        "Smoke test fixture — do not publish. "
        "This article is generated automatically by the CI publication smoke test "
        "to verify that the current AstroPost Pydantic contract produces a file "
        "that passes the Noticiencias front-end validate:content gate. "
        "It covers schema field parity, YAML frontmatter serialization, and the "
        "content quality word-count threshold required by the editorial pipeline. "
        "No editorial content is present in this fixture. "
        "The file is written to a temporary path inside src/content/posts/ and "
        "removed immediately after the validation step completes successfully."
    )
    lines.append("")

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate a minimal AstroPost fixture file."
    )
    parser.add_argument(
        "--output",
        required=True,
        type=Path,
        help="Destination path for the fixture .md file",
    )
    args = parser.parse_args()

    post = build_fixture()
    content = render_frontmatter(post)

    output_path: Path = args.output.resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
    print(f"[fixture] written to {output_path}")


if __name__ == "__main__":
    main()
