name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  quality-gates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: requirements.lock
      - name: Bootstrap environment
        run: make bootstrap
      - name: Lint
        run: make lint
      - name: Type check
        run: make typecheck
      - name: Unit tests
        run: make test
      - name: End-to-end checks
        run: make e2e
      - name: Performance checks
        run: make perf
      - name: Security checks
        run: make security
