name: Dependency lock sync

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  lock-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install pip-tools
        run: python -m pip install pip-tools
      - name: Recompile dependency lock
        run: python -m piptools compile --generate-hashes --output-file requirements.lock requirements.txt
      - name: Ensure lockfile is up to date
        run: git diff --exit-code requirements.lock
