name: Dependency lock sync

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  lock-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Refresh lockfiles (check mode)
        run: python scripts/sync_lockfiles.py --check --install-pip-tools
