name: docs

on:
  pull_request:
    paths:
      - 'README.md'
      - 'docs/**'
      - '.github/workflows/docs.yml'
  push:
    branches:
      - main
    paths:
      - 'README.md'
      - 'docs/**'
      - '.github/workflows/docs.yml'

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linkcheck:
    name: docs/linkcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: docs-pip-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}

      - name: Install linkchecker
        run: |
          python -m pip install --upgrade pip
          python -m pip install linkchecker

      - name: Run link checker
        run: |
          linkchecker --config <(printf "[checking]\nno-follow-url=.*\\.svg$") README.md docs
