name: Mutation Testing

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1"

jobs:
  mutmut:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt mutmut pytest

      - name: Run mutation smoke tests
        run: python -m pytest tests/mutation_smoke

      - name: Run MutMut
        run: |
          mutmut run --CI
          mutmut results
