name: Placeholder Audit (Nightly)

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch: {}

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run full placeholder audit
        id: audit
        run: |
          python -m tools.placeholder_audit --halo 10 --sarif audit.sarif --comment placeholder-report.md --format table
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: audit.sarif
      - name: Upload audit report artifact
        uses: actions/upload-artifact@v4
        with:
          name: placeholder-audit-report
          path: placeholder-report.md
      - name: Publish summary
        run: |
          echo "### Placeholder Audit Summary" >> "$GITHUB_STEP_SUMMARY"
          cat placeholder-report.md >> "$GITHUB_STEP_SUMMARY"
