name: Sync master from main
on:
    push:
        branches: [main]
permissions:
    contents: write
jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
              with: { fetch-depth: 0 }
            - run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
                  git fetch origin main
                  git branch -f master origin/main
                  git push origin master --force
